name:                heural
version:             0.1.0.0
github:              "amuricys/heural"
license:             BSD3
author:              "André Muricy"
maintainer:          "decomuricy@gmail.com"
copyright:           "2020 André Muricy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            side thing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/amurices/heural#readme>

dependencies:
- base >= 4.7 && < 5
- random
- pretty-simple
- tasty
- tasty-hunit
- tasty-quickcheck
- zlib
- bytestring
- vector-sized
- fixed-vector
- vector

library:
  source-dirs: src

executables:
  heural-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heural

tests:
  heural-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heural
